#!/usr/bin/env bash

# This script is a wrapper for starting Hyprland
# Run this instead of calling `Hyprland` directly

# Fix invisible cursor
export WLR_NO_HARDWARE_CURSORS="1";
# Hint electron apps to use wayland
export NIXOS_OZONE_WL="1";

# Wayland session
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=hyprland
export XDG_CURRENT_DESKTOP=hyprland
export XDG_CURRENT_SESSION=hyprland

# GTK environment
export TDESKTOP_DISABLE_GTK_INTEGRATION=1
export CLUTTER_BACKEND=wayland
export BEMENU_BACKEND=wayland
export GTK_MODULES="canberra-gtk-module"

# Firefox
export MOZ_ENABLE_WAYLAND=1

# Qt environment
export QT_QPA_PLATFORMTHEME=qt5ct
# Solve issue with some broken QT apps
export QT_AUTO_SCREEN_SCALE_FACTOR=0
export QT_QPA_PLATFORM=wayland-egl # error with apps xcb
export QT_WAYLAND_FORCE_DPI=physical # use monitor's DPI
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1

# Elementary environment
export ELM_DISPLAY=wl
export ECORE_EVAS_ENGINE=wayland_egl
export ELM_ENGINE=wayland_egl
export ELM_ACCEL=opengl
export ELM_SCALE=1

# SDL environment
export SDL_VIDEODRIVER=wayland

# Java environment
export _JAVA_AWT_WM_NONREPARENTING=1

# LibreOffice
export SAL_USE_VCLPLUGIN=gtk3

# Clutter
export CLUTTER_BACKEND="wayland"

# GDK
export GDK_BACKEND="wayland,x11"

export NO_AT_BRIDGE=1
export WINIT_UNIX_BACKEND=wayland
#export DBUS_SESSION_BUS_ADDRESS
#export DBUS_SESSION_BUS_PID
export XCURSOR_THEME=Adwaita
export XCURSOR_SIZE=24

# Nvidia specific
#if [[ `lspci -k | grep -P 'VGA|3D|Display' | grep -w NVIDIA` ]]; then
#    if [[ `lsmod | grep -w nvidia` ]]; then
#        export GBM_BACKEND=nvidia-drm
#        export __GLX_VENDOR_LIBRARY_NAME=nvidia
#        export LIBVA_DRIVER_NAME=nvidia
#        export WLR_NO_HARDWARE_CURSORS=1
#    fi
#fi

sleep 0.5;
cd ~
exec Hyprland