theme = "kanagawa"

[editor.statusline]
left = ["mode", "spinner", "file-name"]
right = ["diagnostics", "selections", "position", "position-percentage", "file-encoding"]

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor]
bufferline = "multiple"
rulers = [80]
line-number = "relative"
auto-pairs = false

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = false

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.whitespace.render]
tab = "all"

[editor.whitespace.characters]
tab = "→"

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[keys.normal]
# -- NEW -------------------------------
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
# -- FROM VIM --------------------------
"{" = ["goto_prev_paragraph", "extend_to_line_bounds"]
"}" = ["goto_next_paragraph", "extend_to_line_bounds"]
# -- MODIFIED --------------------------
esc = ["collapse_selection", "keep_primary_selection"]
X = ["extend_line_above"]

[keys.select]
# -- NEW -------------------------------
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
# -- FROM VIM --------------------------
"{" = ["goto_prev_paragraph", "extend_to_line_bounds"]
"}" = ["goto_next_paragraph", "extend_to_line_bounds"]
# -- MODIFIED --------------------------
";" = ["collapse_selection", "keep_primary_selection", "normal_mode"]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
X = ["extend_line_above"]

[keys.normal."'"]
"." = "repeat_last_motion"
"`" = "switch_to_uppercase"
"d" = "delete_selection_noyank"
"c" = "change_selection_noyank"
"C" = "copy_selection_on_prev_line"
"s" = "split_selection_on_newline"
#"minus" = "merge_selections"
"_" = "merge_consecutive_selections"
";" = "flip_selections"
#"e" = "move_parent_node_end"
#"b" = "move_parent_node_start"
"x" = "shrink_to_line_bounds"
"u" = "earlier"
"U" = "later"
"J" = "join_selections_space"
"K" = "remove_selections"
"," = "remove_primary_selection"
"(" = "rotate_selection_contents_backward"
")" = "rotate_selection_contents_forward"
":" = "ensure_selections_forward"
"|" = "shell_pipe_to"
"!" = "shell_append_output"

"o" = "expand_selection"
"up" = "expand_selection"
"i" = "shrink_selection"
"down" = "shrink_selection"
"p" = "select_prev_sibling"
"right" = "select_next_sibling"
"n" = "select_next_sibling"
"left" = "select_prev_sibling"
