#!/usr/bin/env bash

get_volume() {
  wpctl get-volume @DEFAULT_AUDIO_SINK@
}

send_notification() {
  volume=$(get_volume)
  if [[ $volume == *"MUTED"* ]]; then
    notify-send -t 100 "Volume Muted"
  else
    notify-send -t 100 "$volume"
  fi
}

inc_volume() {
  wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%+
  send_notification

  # Play change volume sound
  canberra-gtk-play -i audio-volume-change -d "changevolume"
}

dec_volume() {
  wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%-
  send_notification

  # Play change volume sound
  canberra-gtk-play -i audio-volume-change -d "changevolume"
}

toggle_mute() {
  wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
  send_notification
}

if [[ "$1" == "--get" ]]; then
  get_volume
elif [[ "$1" == "--inc" ]]; then
  inc_volume
elif [[ "$1" == "--dec" ]]; then
  dec_volume
elif [[ "$1" == "--toggle" ]]; then
  toggle_mute
else
  echo $(get_volume)%
fi


