#!/usr/bin/env bash

get_volume() {
  wpctl get-volume @DEFAULT_AUDIO_SINK@
}

inc_volume() {
  wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%+
  volume=$(get_volume)
  if [[ $volume == *"MUTED"* ]]; then
    image=~/.config/hypr/dunst/assets/ui/volume_muted.svg
  else
    image=~/.config/hypr/dunst/assets/ui/volume_up.png
  fi

  # Send notification to dunst
  dunstify \
    -a "VOLUME" \
    "$(wpctl get-volume @DEFAULT_AUDIO_SINK@)" \
    -h int:value:"$volume" \
    -i $image \
    -r 2593 \
    -u normal 
    /

  # Play change volume sound
  canberra-gtk-play -i audio-volume-change -d "changevolume"
}

dec_volume() {
  wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%-
  volume=$(get_volume)
  volume=$(get_volume)
  if [[ $volume == *"MUTED"* ]]; then
    image=~/.config/hypr/dunst/assets/ui/volume_muted.svg
  else
    image=~/.config/hypr/dunst/assets/ui/volume_down.png
  fi

  # Send notification to dunst
  dunstify \
    -a "VOLUME" \
    "$(wpctl get-volume @DEFAULT_AUDIO_SINK@)" \
    -h int:value:"$volume" \
    -i $image \
    -r 2593 \
    -u normal 
    /

  # Play change volume sound
  canberra-gtk-play -i audio-volume-change -d "changevolume"
}

toggle_mute() {
  wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

  volume=$(get_volume)
  if [[ $volume == *"MUTED"* ]]; then
    image=~/.config/hypr/dunst/assets/ui/volume_muted.svg
  else
    image=~/.config/hypr/dunst/assets/ui/volume_up.png
  fi

  dunstify \
    -a "VOLUME" \
    "$(wpctl get-volume @DEFAULT_AUDIO_SINK@)" \
    -h int:value:"$volume" \
    -i $image \
    -r 2593 \
    -u normal 
    /
}

if [[ "$1" == "--get" ]]; then
  get_volume
elif [[ "$1" == "--inc" ]]; then
  inc_volume
elif [[ "$1" == "--dec" ]]; then
  dec_volume
elif [[ "$1" == "--toggle" ]]; then
  toggle_mute
else
  echo $(get_volume)%
fi
